### PR TITLE
Added support for Ring Intercom

### PR DESCRIPTION
**Pull request by stefan-schweiger**
Translations were done with deepl, so I hope they are somewhat fine since I only speak German and English.

### CODE REVIEW

**Comment by daneedk** [comment]
Hi Stefan,

I will look into this, but quite busy at the moment so not earlier than somewhere next week.

**Comment by stefan-schweiger** [comment]
Did you have any chance to look at this yet? :) it has been working locally on my Homey pretty well now for the last two weeks. Just a bit unsure if maybe for other people a button type would make more sense instead of a lock (since intercoms autolock after a few seconds usually) and the reverting is a bit hacky.

**Comment by daneedk** [comment]
Unfortunately not, I’m currently ill and not spending time behind a computer currently.

**Comment by stefan-schweiger** [comment]
Don't worry about it, get well soon!

**Comment by stefan-schweiger** [comment]
Hey, hope you are feeling better. Just remembered that we never finished this topic, any chance you find the time over the holidays to look at this? :)

**Comment by daneedk** [comment]
Hi Stefan,

I will try too look into this after Christmas.

Cheers,

Danee

**Comment by daneedk** [comment]
Hi Stefan,

I've published a new version including your pull request to the App Store as test, could you please install it from https://homey.app/a/com.amazon.ring/test/ and test it?
(I expect no problems, but I can't test it since I don't have an Intercom)

Cheers,

Danee

**Comment by stefan-schweiger** [comment]
Thank you very much, will try right away!

**Comment by stefan-schweiger** [comment]
Seems to work just fine like my local dev version did :)

**Comment by daneedk** [comment]
Thanks for testing. Are you on the Homey Community forum? When I publish it I want to mention you in the post but I couldn't found you when searching on Stefan.

**Comment by stefan-schweiger** [comment]
No problem, glad to help :) You can link me with https://community.homey.app/u/staeff

**Comment by daneedk** [comment]
Hi Stefan,

The app is now published and I've created a post on the Ring topic on the forum.

**Pull request merged**
